FROM python:3.9 as build
# Set the working directory
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# Stage 2: Final image
FROM python:3.9-slim
# Set the working directory
WORKDIR /app
# Copy the installed packages from the build stage
COPY --from=build /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
# Copy the application code
COPY  app.py .
EXPOSE 5000
# Run the application
CMD ["python", "app.py"]
